
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p8CTOMgV-ZTs-na-s5CquTd6tOPu5XKa
"""

# Install required Python packages
!pip install -q streamlit python-whois requests google-genai

# Download and set up Cloudflare Tunnel executable
!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -O cloudflared
!chmod +x cloudflared

# Commented out IPython magic to ensure Python compatibility.

# """
# ThreatLens - Threat Intelligence Data Sources
# Provides functions and a central registry for collecting security data.
# Decoupled from UI and AI orchestration logic.
# """
# 
# import os
# import urllib.parse
# from typing import Any, Callable, Dict, Optional
# import requests
# import whois
# 
# VT_API_KEY = os.getenv("VIRUSTOTAL_API_KEY")
# 
# 
# def get_virustotal(target: str, input_type: str, api_key: Optional[str] = None) -> Dict[str, Any]:
#     """Fetches threat analysis data from VirusTotal API v3."""
#     key = api_key or VT_API_KEY or ""
#     if not key:
#         return {
#             "source": "VirusTotal",
#             "status": "error",
#             "data": {},
#             "error": "VirusTotal API Key missing. Enter it in the sidebar.",
#         }
# 
#     headers = {"x-apikey": key, "Accept": "application/json"}
#     base_url = "https://www.virustotal.com/api/v3"
# 
#     try:
#         if input_type == "IP Address":
#             endpoint = f"{base_url}/ip_addresses/{target}"
#         elif input_type == "Domain":
#             endpoint = f"{base_url}/domains/{target}"
#         elif input_type == "URL":
#             import base64
#             url_id = base64.urlsafe_b64encode(target.encode()).decode().strip("=")
#             endpoint = f"{base_url}/urls/{url_id}"
#         else:
#             return {"source": "VirusTotal", "status": "error", "data": {}, "error": f"Unsupported input type: {input_type}"}
# 
#         response = requests.get(endpoint, headers=headers, timeout=10)
# 
#         if response.status_code == 404:
#             return {"source": "VirusTotal", "status": "success", "data": {"message": "Target not found in VirusTotal database."}, "error": None}
#         elif response.status_code != 200:
#             return {"source": "VirusTotal", "status": "error", "data": {}, "error": f"HTTP {response.status_code}: {response.text}"}
# 
#         attributes = response.json().get("data", {}).get("attributes", {})
#         stats = attributes.get("last_analysis_stats", {})
# 
#         return {
#             "source": "VirusTotal",
#             "status": "success",
#             "data": {
#                 "malicious": stats.get("malicious", 0),
#                 "suspicious": stats.get("suspicious", 0),
#                 "harmless": stats.get("harmless", 0),
#                 "undetected": stats.get("undetected", 0),
#                 "reputation": attributes.get("reputation", 0),
#             },
#             "error": None,
#         }
#     except Exception as e:
#         return {"source": "VirusTotal", "status": "error", "data": {}, "error": f"VirusTotal lookup failed: {str(e)}"}
# 
# 
# def get_whois(target: str, input_type: str, api_key: Optional[str] = None) -> Dict[str, Any]:
#     """Fetches WHOIS registration details."""
#     try:
#         query_target = target
#         if input_type == "URL":
#             parsed = urllib.parse.urlparse(target)
#             query_target = (parsed.netloc or parsed.path).split(":")[0]
# 
#         w = whois.whois(query_target)
# 
#         if not w or not any([w.registrar, w.creation_date, w.domain_name]):
#             return {"source": "WHOIS", "status": "error", "data": {}, "error": "WHOIS details unavailable for this target."}
# 
#         def clean_val(val):
#             return [str(v) for v in val] if isinstance(val, list) else (str(val) if val else None)
# 
#         return {
#             "source": "WHOIS",
#             "status": "success",
#             "data": {
#                 "registrar": clean_val(w.registrar),
#                 "creation_date": clean_val(w.creation_date),
#                 "expiration_date": clean_val(w.expiration_date),
#                 "country": clean_val(w.country),
#                 "status": clean_val(w.status),
#             },
#             "error": None,
#         }
#     except Exception as e:
#         return {"source": "WHOIS", "status": "error", "data": {}, "error": f"WHOIS lookup failed: {str(e)}"}
# 
# 
# # SOURCES REGISTRY
# SOURCES: Dict[str, Callable[..., Dict[str, Any]]] = {
#     "VirusTotal": get_virustotal,
#     "WHOIS": get_whois,
# }

# Commented out IPython magic to ensure Python compatibility.

# """
# ThreatLens - Streamlit Application & Orchestrator
# """
# 
# import ipaddress
# import json
# import os
# import re
# import urllib.parse
# from typing import Any, Dict, Optional, Tuple
# import streamlit as st
# from google import genai
# from google.genai import types
# 
# from sources import SOURCES
# 
# st.set_page_config(page_title="ThreatLens", page_icon="🛡️", layout="wide")
# 
# # Sidebar for dynamic API Key inputs
# st.sidebar.header("🔑 API Keys (Optional)")
# vt_key_input = st.sidebar.text_input("VirusTotal API Key", type="password")
# gemini_key_input = st.sidebar.text_input("Gemini API Key", type="password")
# 
# VT_KEY = vt_key_input or os.getenv("VIRUSTOTAL_API_KEY", "")
# GEMINI_KEY = gemini_key_input or os.getenv("GEMINI_API_KEY", "")
# 
# 
# def validate_and_normalize(target: str, input_type: str) -> Tuple[bool, str, str]:
#     cleaned = target.strip()
#     if not cleaned:
#         return False, "", "Input cannot be empty."
# 
#     if input_type == "IP Address":
#         try:
#             return True, str(ipaddress.ip_address(cleaned)), ""
#         except ValueError:
#             return False, "", "Invalid IP format (e.g., 8.8.8.8)."
# 
#     elif input_type == "Domain":
#         cleaned = re.sub(r"^https?://", "", cleaned, flags=re.IGNORECASE).split("/")[0].split(":")[0]
#         if re.match(r"^(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?\.)+[a-zA-Z]{2,}$", cleaned):
#             return True, cleaned.lower(), ""
#         return False, "", "Invalid Domain format (e.g., example.com)."
# 
#     elif input_type == "URL":
#         if not re.match(r"^https?://", cleaned, re.IGNORECASE):
#             cleaned = "http://" + cleaned
#         parsed = urllib.parse.urlparse(cleaned)
#         if parsed.scheme in ["http", "https"] and parsed.netloc:
#             return True, cleaned, ""
#         return False, "", "Invalid URL format."
# 
#     return False, "", "Unknown input type."
# 
# 
# def build_gemini_prompt(results: Dict[str, Any], input_type: str, target: str, level: str) -> str:
#     instructions = {
#         "Beginner": "Explain threat status without jargon. Highlight findings simply with practical advice.",
#         "Intermediate": "Provide technical analysis including detection metrics, WHOIS details, and investigation steps.",
#         "Expert": "Deliver SOC-level threat analysis covering detection ratios, anomalies, and remediation strategies.",
#     }
#     return f"""
#     Analyze threat intelligence data for '{target}' ({input_type}).
#     Target Audience: {level} - {instructions.get(level, '')}
# 
#     Raw Data:
#     {json.dumps(results, indent=2)}
# 
#     Return strict JSON:
#     {{
#         "verdict": "Safe" | "Suspicious" | "Malicious" | "Unknown",
#         "confidence": "Low" | "Medium" | "High",
#         "summary": "Short summary",
#         "key_findings": ["Finding 1"],
#         "risk_factors": ["Risk factor 1"],
#         "recommendation": "Recommended action"
#     }}
#     """
# 
# 
# def analyze_with_gemini(prompt: str, api_key: str) -> Tuple[Optional[Dict[str, Any]], Optional[str]]:
#     if not api_key:
#         return None, "Gemini API Key missing. Enter it in the sidebar to generate AI Insights."
#     try:
#         client = genai.Client(api_key=api_key)
#         response = client.models.generate_content(
#             model="gemini-3.6-flash",
#             contents=prompt,
#             config=types.GenerateContentConfig(response_mime_type="application/json"),
#         )
#         return json.loads(response.text), None
#     except Exception as e:
#         return None, f"Gemini error: {str(e)}"
# 
# 
# def main():
#     st.title("ThreatLens")
#     st.caption("Lightweight IP, Domain & URL Threat Intelligence Analyzer")
# 
#     col1, col2, col3 = st.columns([1, 2, 1])
#     with col1:
#         input_type = st.selectbox("Target Type", ["IP Address", "Domain", "URL"])
#     with col2:
#         target_input = st.text_input("Target Input", placeholder="e.g., 8.8.8.8 or example.com")
#     with col3:
#         knowledge_level = st.selectbox("Knowledge Level", ["Beginner", "Intermediate", "Expert"])
# 
#     if st.button("Analyze Target", type="primary", use_container_width=True):
#         is_valid, normalized_target, err_msg = validate_and_normalize(target_input, input_type)
#         if not is_valid:
#             st.error(err_msg)
#             return
# 
#         collected_results = {}
#         with st.spinner("Fetching data from registered sources..."):
#             for source_name, source_func in SOURCES.items():
#                 key = VT_KEY if source_name == "VirusTotal" else None
#                 collected_results[source_name] = source_func(normalized_target, input_type, api_key=key)
# 
#         with st.spinner("Generating AI Analysis..."):
#             prompt = build_gemini_prompt(collected_results, input_type, normalized_target, knowledge_level)
#             ai_data, ai_error = analyze_with_gemini(prompt, GEMINI_KEY)
# 
#         st.markdown("---")
#         if ai_data:
#             verdict = ai_data.get("verdict", "Unknown")
#             colors = {"Safe": "green", "Suspicious": "orange", "Malicious": "red", "Unknown": "gray"}
#             st.markdown(f":{colors.get(verdict, 'gray')}[### VERDICT: {verdict.upper()} (Confidence: {ai_data.get('confidence', 'N/A')})]")
# 
#             st.subheader("AI Insight")
#             st.write(ai_data.get("summary", ""))
# 
#             c1, c2 = st.columns(2)
#             with c1:
#                 st.markdown("**Key Findings**")
#                 for kf in ai_data.get("key_findings", []):
#                     st.write(f"- {kf}")
#             with c2:
#                 st.markdown("**Risk Factors**")
#                 for rf in ai_data.get("risk_factors", []):
#                     st.write(f"- {rf}")
# 
#             st.info(f"**Recommendation:** {ai_data.get('recommendation', 'N/A')}")
#         else:
#             st.warning(ai_error)
# 
#         st.markdown("---")
#         st.subheader("Source Results")
#         sc1, sc2 = st.columns(2)
# 
#         with sc1:
#             st.markdown("### VirusTotal")
#             vt = collected_results.get("VirusTotal", {})
#             if vt.get("status") == "error":
#                 st.error(vt.get("error"))
#             else:
#                 st.json(vt.get("data", {}))
# 
#         with sc2:
#             st.markdown("### WHOIS")
#             wh = collected_results.get("WHOIS", {})
#             if wh.get("status") == "error":
#                 st.error(wh.get("error"))
#             else:
#                 st.json(wh.get("data", {}))
# 
# 
# if __name__ == "__main__":
#     main()

import os
import subprocess
import time

# 1. Old processes clear karein
!pkill -f streamlit
!pkill -f cloudflared

# 2. Streamlit ko background me launch karein
subprocess.Popen(
    ["streamlit", "run", "app.py", "--server.port", "8501", "--server.headless", "true"]
)
time.sleep(5)

# 3. Cloudflare tunnel launch karke direct link print karein
print("\n--- LINK IS CREATING, WAIT 5 SECONDS ---")
!./cloudflared tunnel --url http://127.0.0.1:8501 2>&1 | grep -o 'https://.*\.trycloudflare\.com'
